language: java
jdk:
  - openjdk11
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash)


deploy:
  provider: heroku
  api_key: 32245718-48ba-4a4c-88cd-df01847e4ed0
    app: lkjaffl